auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("new", views.new_listing, name="new_listing"),
    path('listing/<int:listing_id>', views.listing, name="listing"),
    path('watchlist', views.watchlist, name="watchlist"),
    path('close', views.close, name="close"),
    path('comments', views.comments, name="comments"),
    path('categories', views.categories, name="categories"),
    path('category/<str:name>', views.category, name='category'),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

# helps in stoping caching of static files
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import cache_control
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]


# stops caching of static files
# https://stackoverflow.com/a/54222112/6008082
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=cache_control(no_cache=True, must_revalidate=True)(serve))

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Represents our user
class User(AbstractUser):
    watchlist = models.ManyToManyField('Listings', blank = True, related_name="watchlist_users")

    def __str__(self):
        return f"{self.username}"


# Represent a product listing
class Listings(models.Model):
    # user who created the listing
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "listings")
    # title of the listing
    title = models.CharField(max_length = 64)
    description = models.CharField(max_length = 280)
    current_price = models.DecimalField(max_digits = 9 ,decimal_places = 2)
    # category
    category = models.ForeignKey('Categories', on_delete = models.CASCADE, related_name="listings")
    image_url = models.URLField(blank = True)
    # store status of listing - open(True) or close(False)
    active = models.BooleanField(default = True)
    # time and date of Creation
    datetime = models.DateTimeField(auto_now_add = True)
    # winner of listing
    winner = models.ForeignKey(User, on_delete = models.SET_NULL, null = True, blank = True, related_name="purchased_listings")

    def __str__(self):
        return f"{self.title} by {self.user} at {self.current_price}"


# Represents bids on diffrent listings
class Bids(models.Model):
    # user who bidded this price
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "bids")
    # listing on which bid is made
    listing = models.ForeignKey(Listings, on_delete = models.CASCADE, related_name = "bids")
    # price of bid
    price = models.DecimalField(max_digits = 9 ,decimal_places = 2)

    # only save the bid if it follow the desired conditions
    def save(self, *args, **kwargs):
        # bid price should be more than current price of listing and the listing must be active
        if self.listing.current_price > self.price or not self.listing.active:
            return None
        self.listing.current_price = self.price
        self.listing.save()
        print(self.listing.current_price)
        super().save(*args, **kwargs)
        return True


    def __str__(self):
        return f"${self.price} on {self.listing.title} by {self.user}"



# Represents Comments on different product listings
class Comments(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "comments")
    listing = models.ForeignKey(Listings, on_delete = models.CASCADE, related_name = "comments")
    comment = models.CharField(max_length = 140)
    datetime = models.DateTimeField(auto_now = True)

    def __str__(self):
        return f"'{self.comment}' on {self.listing.title} by {self.user}"


class Categories(models.Model):
    name = models.CharField(max_length = 64, default = "Not Specified", unique = True)

    def __str__(self):
        return f"Category: {self.name}"

auctions/forms.py
from django import forms
from .models import Listings, Bids, Comments

class NewListingForm(forms.ModelForm):
    category = forms.CharField(max_length = 64, required=False)
    class Meta:
        model = Listings
        fields = ['title', 'description', 'current_price', 'image_url']

class BidForm(forms.ModelForm):
    class Meta:
        model = Bids
        fields = ['price']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['comment']

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError, models
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required

from .models import *
from .forms import NewListingForm, BidForm, CommentForm


def index(request):
    return render(request, "auctions/index.html", {
        'listings': Listings.objects.all()
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        if request.user.is_authenticated:
            return render(request, "auctions/index.html", {
                'listings': Listings.objects.all()
            })
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


# Creates a new listing
@login_required(redirect_field_name="", login_url=reverse_lazy('auctions:login'))
def new_listing(request):
    if request.method == "POST":
        form = NewListingForm(request.POST)

        if not form.is_valid():
            return render(request, 'auctions/newlisting.html', {"form": form})

        if form.cleaned_data['category']:
            try:
                # if category already exists then use that
                category = Categories.objects.get(
                    name=form.cleaned_data['category'])
            except Categories.DoesNotExist:
                # else create new
                category = Categories(name=form.cleaned_data['category'])
        else:
            try:
                # if no name provided check if Not Specified category exist
                category = Categories.objects.get(name="Not Specified")
            except Categories.DoesNotExist:
                # otherwise make a new Not Specified Category
                category = Categories()

        category.save()
        new_product_listing = Listings(user=request.user, title=form.cleaned_data['title'], description=form.cleaned_data[
                                       'description'], current_price=form.cleaned_data['current_price'], category=category)

        if form.cleaned_data['image_url']:
            new_product_listing.image_url = form.cleaned_data['image_url']

        new_product_listing.save()

        return HttpResponseRedirect(reverse('auctions:listing', args=(new_product_listing.id,)))

    else:
        return render(request, 'auctions/newlisting.html')


def listing(request, listing_id):
    listing = Listings.objects.get(pk=listing_id)

    try:
        if request.user.is_authenticated:
            watchlist = request.user.watchlist.get(pk=listing_id)
        else:
            watchlist = None
    except Listings.DoesNotExist:
        watchlist = None

    # make a bid
    if request.method == "POST":
        bid_form = BidForm(request.POST)

        if not bid_form.is_valid():
            return render(request, 'auctions/listing.html', {
                "listing": listing,
                "watchlist": watchlist,
                "bid_form": bid_form,
                "comments": listing.comments.all(),
            })

        # add bid in database
        bid = Bids(user=request.user, listing=listing,
                   price=bid_form.cleaned_data['price'])
        # save and check status
        if bid.save() is None:
            return render(request, 'auctions/listing.html', {
                "listing": listing,
                "watchlist": watchlist,
                "bid_form": bid_form,
                "bid_error": "Make a bid higher than current price",
                "comments": listing.comments.all(),
            })

    return render(request, 'auctions/listing.html', {
        "listing": listing,
        "watchlist": watchlist,
        "bid_form": BidForm(),
        "comments": listing.comments.all(),
    })


@login_required(redirect_field_name="", login_url=reverse_lazy('auctions:login'))
def watchlist(request):
    if request.method == "POST":
        watchlist_option = str(request.POST["watchlist_option"])
        listing_id = int(request.POST["listing_id"])

        try:
            listing = request.user.watchlist.get(pk=listing_id)
        except Listings.DoesNotExist:
            listing = Listings.objects.get(pk=listing_id)

        if watchlist_option == "remove":
            request.user.watchlist.remove(listing)
        elif watchlist_option == "add":
            request.user.watchlist.add(listing)

        return HttpResponseRedirect(reverse('auctions:listing', args=(listing_id,)))
    else:
        return render(request, 'auctions/watchlist.html', {
            "watchlist": request.user.watchlist.all(),
        })


@login_required(redirect_field_name="", login_url=reverse_lazy('auctions:login'))
def close(request):
    if request.method == "POST":
        listing_id = request.POST["listing_id"]
        listing = Listings.objects.get(pk=listing_id)

        highest_bid = listing.bids.get(price=listing.current_price)

        listing.active = False
        listing.winner = highest_bid.user
        listing.save()

        return HttpResponseRedirect(reverse('auctions:listing', args=(listing_id, )))
    else:
        return HttpResponseRedirect(reverse('auctions:index'))


@login_required(redirect_field_name="", login_url=reverse_lazy('auctions:login'))
def comments(request):
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        listing = Listings.objects.get(pk=request.POST['listing_id'])
        if not comment_form.is_valid():
            return render(request, 'auctions/listing.html', {
                "listing": listing,
                "watchlist": request.user.watchlist.get(pk=listing.id),
                "bid_form": BidForm(),
                "comments": listing.comments.all(),
                "comment_form": comment_form,
            })

        comment_text = comment_form.cleaned_data['comment']
        comment = Comments(user=request.user,
                           listing=listing, comment=comment_text)
        comment.save()

        return HttpResponseRedirect(reverse('auctions:listing', args=(listing.id,)))
    else:
        return HttpResponseRedirect(reverse('auctions:index'))


@login_required(redirect_field_name="", login_url=reverse_lazy('auctions:login'))
def categories(request):
    nonempty_categories = Categories.objects.all()
    nonempty_categories = [
        item for item in nonempty_categories if len(item.listings.all()) > 0]

    return render(request, 'auctions/categories.html', {
        "categories": sorted(nonempty_categories, key=lambda category: category.name),
    })


def category(request, name):
    category = Categories.objects.get(name=name)

    return render(request, 'auctions/category.html', {
        'category': category,
        'category_listings': category.listings.all(),
    })

auctions/templates/auctions/categories.html
{% extends 'auctions/layout.html' %}

{% block title %}
    Categories
{% endblock %}

{% block main %}
    <h2 class="pt-3 pb-3 text-center display-4">Categories</h2>

    <ul class="list-group text-center" id="categories">
        {% for category in categories %}
            <a href="{% url 'auctions:category' category.name %}" class="text-decoration-none">
                <li class="list-group-item p-4 lead">
                    {{category.name}}
                </li>
            </a>
        {% empty %}
            <div class="alert alert-secondary">No Category Exists Yet</div>
        {% endfor %}
    </ul>
{% endblock %}

auctions/templates/auctions/category.html
{% extends 'auctions/layout.html' %}

{% block title %}
    category.name
{% endblock %}

{% block main %}
<h2 class="pt-3 pb-3 text-center display-4">All {{category.name}}</h2>

<ul class="list-group text-center" id="category_listings">
    {% for listing in category_listings %}
        <a href="{% url 'auctions:listing' listing.id %}" class="text-decoration-none">
            <li class="list-group-item p-4 lead">
                {{listing.title}} at ${{listing.current_price}}
            </li>
        </a>
    {% empty %}
        <div class="alert alert-secondary">No Item in Category</div>
    {% endfor %}
</ul>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load humanize %}

{% block main %}
    <h2 class="pt-3 pb-3 text-center display-4">Active Listings</h2>

    {% if listings %}
        <div class="card-columns" id="listing-display">
            {% for listing in listings %}

            <div class="card">
                {% if listing.image_url %}
                    <img class="card-img-top" src="{{listing.image_url}}" alt="{{listing.title}} product">
                {% else %}
                    <div class="card-header text-center">No Image Available</div>
                {% endif %}
                <div class="card-body">
                    <h4 class="card-title">
                        {{listing.title}}
                        <span class="badge badge-secondary badge-pill">at ${{listing.current_price | intcomma}}</span>
                    </h4>
                    <p class="card-text">{{listing.description}}</p>
                    <a href="{% url 'auctions:listing' listing.pk %}" class="btn btn-sm btn-outline-dark stretched-link">See More</a>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="alert alert-warning text-center">No Listing Available</div>
    {% endif %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Auctions{% endblock %}</title>

        <!-- CSS only -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <!-- JS, Popper.js, and jQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <header class="border-bottom">
            <nav class="navbar navbar-expand-md bg-light navbar-light w-100" role="navigation">
                <a href="{% url 'auctions:index' %}" class="navbar-brand">Auctions</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div id="main-nav" class="collapse navbar-collapse justify-content-between">
                    <div><!--Proxy element for space--></div>
                    <ul class="navbar-nav pr-3">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'auctions:new_listing' %}">Create Listing</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                    <div>
                        {% if user.is_authenticated %}
                            Signed in as <strong>{{ user.username }}</strong>
                        {% else %}
                            Not signed in
                        {% endif %}
                    </div>
                </div>
            </nav>
        </header>
        
        <main class="container"> 
            {% block main %}
            {% endblock %}
        </main>
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends 'auctions/layout.html' %}

{% block title %}
{{listing.title}}
{% endblock %}


{% block main %}
<div class="row pt-2">
    <div class="col-lg-6">
        {% if listing.image_url %}
        <div class="text-center">
            <img src="{{listing.image_url}}" alt="{{listing.title}}'s photo" class="img-fluid">
        </div>
        {% else %}
        <div class="d-flex mx-auto rounded text-center align-items-center bg-danger" style="width: 330px;height:300px;">
            <h1>No Image Available</h1>
        </div>
        {% endif %}
    </div>
    <div class="col-lg-6">
        <ol class="list-group mt-2 h-100 justify-content-around" id="listing-info">
            <li class="list-group-item shadow rounded text-danger">Current Price: ${{listing.current_price}}</li>
            <li class="list-group-item shadow rounded">By: {{listing.user}}</li>
            <li class="list-group-item shadow rounded">Category: {{listing.category.name}}</li>
            <li class="list-group-item shadow rounded">Posted: {{listing.datetime}}</li>
        </ol>
    </div>
</div>
<div class="row mt-3">
    <div class="col-lg-6 text-center">
        <div id="listing-desc" class="bg-info rounded card text-break">
            <h1 class="card-header">{{listing.title}}</h1>
            <div class="p-3 lead card-body">Description: {{listing.description}}</div>
        </div>
    </div>
    <div class="col-lg-6 d-flex text-center flex-column">
        <div id="actions" class="d-flex flex-column justify-content-center h-100">
            {% if request.user.is_authenticated and listing.active and request.user != listing.user %}
                {% if watchlist %}
                <form action="{% url 'auctions:watchlist' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="watchlist_option" value="remove">
                    <input type="hidden" name="listing_id" value="{{listing.id}}">
                    <input type="submit" value="Remove From Watchlist" class="btn btn-dark btn-block">
                </form>
                {% else %}
                <form action="{% url 'auctions:watchlist' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="watchlist_option" value="add" required>
                    <input type="hidden" name="listing_id" value="{{listing.id}}" required>
                    <input type="submit" value="Add to Watchlist" class="btn btn-dark btn-block">
                </form>
                {% endif %}
                <div id="bid-form">
                    {% include 'auctions/snippets/form_error.html' with  errors=bid_form.non_fields_errors %}
                    <form action="{% url 'auctions:listing' listing.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-group mt-3 input-group">
                            {% include 'auctions/snippets/form_error.html' with errors=bid_form.price.errors %}
                            <div class="input-group-prepend">
                                <label for="id_price" class="input-group-text">Bid</label>
                            </div>
                            <input type="number" name="price" id="id_price" step="0.01" class="form-control"
                                placeholder="Make a Bid" required value="{{bid_form.price.value}}">
                        </div>
                        <input type="submit" value="Make Bid" class="btn btn-dark btn-block">
                    </form>
                    {%if bid_error %}
                        <div class="alert alert-danger">{{bid_error}}</div>
                    {% endif %}
                </div>
            {% elif request.user.is_authenticated and request.user == listing.user and listing.active %}
                <form action="{% url 'auctions:close' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="listing_id" value="{{listing.id}}">
                    <input type="submit" name="close_listing" value="Close This Listing" class="btn btn-dark btn-block">
                </form>
            {% elif not listing.active and  request.user.is_authenticated %}
                <div class="alert alert-danger">Listing has been closed.</div>
                {% if listing.winner == request.user %}
                    <div class="alert alert-success">You have won this listing</div>
                {% endif %}
            {% else %}
            <div class="alert alert-warning">Login to Add to Wishlist</div>
            <div class="alert alert-warning">Login to Make a Bid</div>
            {% endif %}
        </div>
    </div>
</div>

<div class="comment-block mt-4 mb-4">
    <h2 class="text-center">Comments</h2>
    {% if request.user.is_authenticated %}
        {% include 'auctions/snippets/form_error.html' with errors=comment_form.non_field_errors %}
        <form action="{% url 'auctions:comments' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="listing_id" value="{{listing.id}}">
            <div class="form-group">
                {% include 'auctions/snippets/form_error.html' with errors=comment_form.comment.errors %}
                <textarea type="text" name="comment" id="id_comment"class="form-control" required>{{comment_form.comment.value}}</textarea>
            </div>
            <input type="submit" value="Comment" class="btn btn-dark form-control">
        </form>
    {% else %}
        <div class="alert alert-warning text-center">Login to Comment</div>
    {% endif %}

    <div class="comments mt-3">
        {% for comment in comments %}
            <div class="media border p-3">
                <div class="media-body">
                <h4><span class="m-1">{{comment.user}}</span><small><i>(Posted on {{comment.datetime}})</i></small></h4>
                <p>{{comment.comment}}</p>
                </div>
            </div>
        {% empty %}
            <div class="alert alert-secondary text-center">No Comments Yet</div>
        {% endfor %}
    </div>
</div>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block title %}
    Login
{% endblock %}

{% block main %}

    <h1 class="pt-3 pb-3 text-center display-4">Login</h1>

    <div class="bg-dark text-light p-3 rounded-lg m-auto" id="login-form">

        {% if message %}
            <div class="alert alert-info">{{ message }}</div>
        {% endif %}
    
        <form action="{% url 'auctions:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Username</label>
                <input autofocus class="form-control" type="text" name="username" id="id_username" placeholder="Username">
            </div>
            <div class="form-group">
                <label for="id_password">Password</label>
                <input class="form-control" type="password" name="password" id="password" placeholder="Password">
            </div>
            <input class="btn btn-primary d-block m-auto" type="submit" value="Login">
        </form>
    
        <div class="text-center mt-2">
            Don't have an account? <a class="text-success" href="{% url 'auctions:register' %}">Register here.</a>
        </div>    
    </div>

{% endblock %}

auctions/templates/auctions/newlisting.html
{% extends 'auctions/layout.html' %}

{% block title %}
    Create New Listing
{% endblock %}

{% block main %}
    <h1 class="pt-3 pb-3 text-center display-4">Create a New Listing</h1>

    <div id="create-new-listing" class="m-auto bg-dark text-light p-3 rounded-lg">
        {% include 'auctions/snippets/form_error.html' with errors=form.non_field_errors %}
        <form action="{% url 'auctions:new_listing' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">Title</label>
                {% include 'auctions/snippets/form_error.html' with errors=form.title.errors %}
                <input type="text" name="title" id="id_title" class="form-control" required value="{{form.title.value}}">
            </div>
            <div class="form-group">
                <label for="id_description">Description</label>
                {% include 'auctions/snippets/form_error.html' with errors=form.description.errors %}
                <textarea name="description" id="id_description" class="form-control" rows="4" required>{{form.description.value}}</textarea>
            </div>
            <div class="form-group">
                <label for="id_current_price">Starting Bid($)</label>
                {% include 'auctions/snippets/form_error.html' with errors=form.current_price.errors %}
                <input type="number" name="current_price" id="id_starting_bid" class="form-control" step = "0.01" required value="{{form.current_price.value}}" maxlength="9">
            </div>
            <div class="form-group">
                <label for="id_category">Category(Optional)</label>
                {% include 'auctions/snippets/form_error.html' with errors=form.category.errors %}
                <input type="text" name="category" id="id_category" class="form-control" value="{{form.category.value}}">
            </div>
            <div class="form-group">
                <label for="id_image_url">Image URL(Optional)</label>
                {% include 'auctions/snippets/form_error.html' with errors=form.image_url.errors %}
                <input type="url" name="image_url" id="id_image_url" class="form-control" value="{{form.image_url.value}}">
            </div>
            <input type="submit" class="btn btn-light d-block m-auto" value="Add Listing">
        </form>
    </div>

    {% if message %}
    <div class="alert alert-success">{{message}}</div>
    {% endif %}
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block main %}

    <h1 class="pt-3 pb-3 text-center display-4">Register</h1>

    <div class="bg-dark text-light p-3 rounded-lg m-auto" id="register-form">

        {% if message %}
            <div class="alert alert-info">{{ message }}</div>
        {% endif %}
    
        <form action="{% url 'auctions:register' %}" method="post" id="register-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Username</label>
                <input class="form-control" autofocus type="text" name="username" id="id_username" placeholder="Username">
            </div>
            <div class="form-group">
                <label for="id_email">Email</label>
                <input class="form-control" type="email" name="email" id="id_email" placeholder="Email Address">
            </div>
            <div class="form-group">
                <label for="id_password">Password</label>
                <input class="form-control" type="password" name="password" id="id_password" placeholder="Password">
            </div>
            <div class="form-group">
                <label for="id_confirmation">Confirm Password</label>
                <input class="form-control" type="password" name="confirmation" id="id_confirmation" placeholder="Confirm Password">
            </div>
            <input class="btn btn-primary d-block m-auto" type="submit" value="Register">
        </form>
    
        <div class="text-center mt-2">
            Already have an account? <a class="text-success" href="{% url 'auctions:login' %}">Log In here.</a>
        </div>
    </div>

{% endblock %}